# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10FVocm1KlLXblgsACWI2L3_h_9vt-LOu
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/healthcare_raw.csv")

df

df.info()

df["Admission_Type"]=df["Admission_Type"].str.lower()

df["Medical_Code"]=df["Medical_Code"].fillna("Undefind")

df.isnull()

df.info()

df['Admission_Type'].value_counts()

df['Admission_Date']=df['Admission_Date'].astype('datetime64[ns]')
df['Discharge_Date']=df['Discharge_Date'].astype('datetime64[ns]')

df["Hospital_stay_Days"]=(df['Discharge_Date'] - df['Admission_Date']).dt.days
df.head()

df[['Admission_Date', 'Medical_Code','Discharge_Date','Admission_Type','Hospital_stay_Days']].head()

df['Billing_Amount'].describe()

df["Medical_Condition"].value_counts()

df["Hospital_stay_Days"].describe()

pd.crosstab(
    df['Admission_Type'],
    df['Medical_Condition']
)

df.groupby('Medical_Condition')['Age'].mean()

